version: '2'

services:

  owncloud:
    image: owncloud
    ports:
      - 8080:80
    links:
      - mysql

  mysql:
    hostname: mysql
    volumes_from:
      - data
    image: mysql
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: owncloud

  data:
    image: mysql
    volumes:
      - /var/lib/mysql
    command: "true"  

