version: '2'

services:

  owncloud:
    build: ./nginx/
    ports:
      - 8080:80
    links:
      - php
    volumes_from:
      - app

  php:
    build: ./php/
    expose:
      - 9000
    links:
      - mysql
    volumes_from:
      - app
  app: 
    image: php:7.0.5-fpm-alpine
    volumes:
      - ./owncloud/:/var/www/html
    command: "true"  

  mysql:
    hostname: mysql
    volumes_from:
      - data
    image: mysql
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: owncloud

  data:
    image: mysql
    volumes:
      - /var/lib/mysql
    command: "true"  
